config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  resources :products, only: %i(index show)
  resources :categories, only: :show
  resources :carts, only: :index
  resources :orders, only: %i(index new create show)
  devise_for :users
  resource :user, only: :show
  namespace :admin do
    root "static_pages#home"

    resources :products
    resources :orders, only: %i(index show)
    resources :categories

    put "approve/:id", to: "orders#approve", as: :approve
    put "reject/:id", to: "orders#reject", as: :reject
  end

  get "add_cart/:product_id", to: "carts#add_cart", as: :add_cart
  get "remove_cart/:product_id", to: "carts#remove_cart", as: :remove_cart
  post "update_subtotal/", to: "carts#update_subtotal", as: :update_subtotal
  put "cancel/:id", to: "orders#cancel", as: :cancel
  get "filter/", to: "products#filter", as: :filter
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  enum status: {processing: 0, ordered: 1, rejected: 2, cancelled: 3}

  belongs_to :user
  has_many :order_details, dependent: :destroy
  has_many :products, through: :order_details

  validates :receiver, presence: true, length: {maximum: Settings.name.length.maximum}
  validates :phone, :address, presence: true

  scope :newest, ->{order created_at: :desc}
  scope :by_product_id, ->(product_id) do
    joins(:order_details).where("order_details.product_id = ?", product_id)
  end
  scope :in_processing, ->{where status: :processing}
end

app/controllers/admin/orders_controller.rb
# frozen_string_literal: true

class Admin::OrdersController < AdminController
  load_and_authorize_resource
  before_action :load_order, only: %i(show approve reject)
  before_action :load_orders, only: %i(index approve reject)

  def index; end

  def show; end

  def approve
    ActiveRecord::Base.transaction do
      @order.ordered!
      @order.order_details.find_each do |order_detail|
        raise t(".not_enough") if order_detail.product.quantity < order_detail.quantity
        decrement_product_quantity order_detail.product, order_detail.quantity
      end
      OrderMailer.approve_order(@order).deliver_now
      respond_to_format
    end
  rescue StandardError => e
    flash[:danger] = t ".cant_approve_now"
    flash[:danger] = t ".not_enough_quantity" if e.message == t(".not_enough")
    redirect_to admin_orders_path
  end

  def reject
    ActiveRecord::Base.transaction do
      @order.rejected!
      OrderMailer.reject_order(@order).deliver_now
      respond_to_format
    end
  rescue StandardError
    flash[:danger] = t ".cant_reject_now"
    redirect_to admin_orders_path
  end

  private

  def load_orders
    @orders = Order.newest
                   .paginate page: params[:page], per_page: Settings.paginate.order.per_page
  end

  def load_order
    @order = Order.find_by id: params[:id]
    return if @order
    flash[:danger] = t ".couldnt_found"
    redirect_to admin_orders_path
  end

  def decrement_product_quantity product, quantity
    product.update quantity: product.quantity - quantity
  end

  def respond_to_format
    respond_to do |format|
      format.html{render "orders/index"}
      format.json {}
      format.js
    end
  end
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  before_action :authenticate_user!, :load_products_in_cart, :load_quantity_in_cart, only: %i(index new create show)
  load_and_authorize_resource
  before_action :check_cart, only: :create
  before_action :load_orders, only: %i(index cancel)
  before_action :load_order, only: %i(cancel show)

  def index; end

  def show; end

  def new
    @order = Order.new
  end

  def create
    ActiveRecord::Base.transaction do
      @order = Order.new order_params
      if @order.save!
        @products_in_cart.each do |product|
          unit_price = product.price
          total_price = product.quantity_in_cart * unit_price
          order_detail = @order.order_details.new(order_id: @order.id, product_id: product.id,
            quantity: product.quantity_in_cart, unit_price: unit_price, total_price: total_price)
          order_detail.save!
        end
        OrderMailer.order_successful(current_user, @order).deliver_now
        after_order_successful
      end
    end
  rescue StandardError
    flash.now[:danger] = t ".order_failed"
    render :new
  end

  def cancel
    if @order.cancelled!
      OrderMailer.cancel_order(current_user, @order).deliver_now
      respond_to do |format|
        format.html{render "orders/index"}
        format.json {}
        format.js
      end
    else
      flash.now[:danger] = t ".cant_cancel_now"
      render :index
    end
  end

  private

  def order_params
    params.require(:order).permit :user_id, :price, :receiver, :phone, :address
  end

  def after_order_successful
    flash[:success] = t ".order_successful"
    reset_cart
    redirect_to root_path
  end

  def check_cart
    return unless is_empty_cart?
    flash[:danger] = t ".empty_cart"
    redirect_to carts_path
  end

  def load_order
    @order = Order.find_by id: params[:id]
    return if @order
    flash[:danger] = t ".couldnt_found"
    redirect_to orders_path
  end

  def load_orders
    @orders = current_user.orders.newest
                          .paginate page: params[:page], per_page: Settings.paginate.order.per_page
  end
end

app/views/admin/orders/_order.html.erb
<tr>
  <td><%= index_count_page order_counter, params[:page], Settings.paginate.order.per_page %></td>
  <td><%= order.receiver %></td>
  <td><%= order.address %></td>
  <td><%= order.phone %></td>
  <td><%= l order.created_at, format: t("date.format.date_time") %></td>
  <td><%= order.status %></td>
  <td><%= number_to_currency order.price %></td>
  <td>
    <%= link_to admin_order_path(order), class: "btn btn-primary" do %>
      <i class="glyphicon glyphicon-zoom-in"></i>&nbsp;<%= t ".detail" %>
    <% end %>
    <% if order.processing? %>
      <%= link_to admin_approve_path(order.id), remote: true, method: :put,
        class: "btn btn-success" do %>
        <i class="glyphicon glyphicon-ok"></i>&nbsp;<%= t ".approve" %>
      <% end %>
      <%= link_to admin_reject_path(order.id), remote: true, method: :put,
        class: "btn btn-danger" do %>
        <i class="glyphicon glyphicon-remove"></i>&nbsp;<%= t ".reject" %>
      <% end %>
    <% end %>
  </td>
</tr>

app/views/admin/orders/approve.js.erb
$('#orders').html('<%= escape_javascript(render @orders) %>');

app/views/admin/orders/index.html.erb
<% provide :title, t(".order_list") %>
<div class="row">
  <div class="col-md-12">
    <h3><%= t ".order_list" %></h3>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th><%= t ".no_number" %></th>
          <th><%= t ".receiver" %></th>
          <th><%= t ".address" %></th>
          <th><%= t ".phone" %></th>
          <th><%= t ".date" %></th>
          <th><%= t ".status" %></th>
          <th><%= t ".total" %></th>
          <th><%= t ".action" %></th>
        </tr>
      </thead>
      <tbody id="orders">
        <%= render @orders %>
        <%= will_paginate %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/orders/reject.js.erb
$('#orders').html('<%= escape_javascript(render @orders) %>');

app/views/admin/orders/show.html.erb
<%= provide :title, t(".order_detail") %>
<h1><%= t ".order_detail" %></h1>
<div class="container">
  <div class="row pad-top-botm client-info">
    <div class="col-lg-6 col-md-6 col-sm-6">
      <h4><strong><%= t ".customer_info" %></strong></h4>
      <strong><%= t ".name" %></strong><%= @order.receiver %>
      <br>
      <b><%= t ".address" %></b><%= @order.address %>
      <br>
      <b><%= t ".call" %></b><%= @order.phone %>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-6">
      <h4><strong><%= t ".payment_details" %></strong></h4>
      <b><%= t ".bill_amount" %></b> <%= number_to_currency @order.price %>
      <br>
      <b><%= t ".purchase_date" %></b>
      <%= l @order.created_at, format: t("date.format.date_time") %>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12">
      <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover">
          <thead>
            <tr>
              <th><%= t ".items" %></th>
              <th><%= t ".quantity" %></th>
              <th><%= t ".unit_price" %></th>
              <th><%= t ".sub_total" %></th>
            </tr>
          </thead>
          <tbody>
            <%= render @order.order_details %>
          </tbody>
          <tfoot>
            <tr>
              <th colspan="3"><%=  t ".total_price" %></th>
              <th><%= number_to_currency @order.price %></th>
            </tr>
          </tfoot>
        </table>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div><%= link_to t(".back"), admin_orders_path, class: "btn btn-primary pull-left" %></div>
    </div>
  </div>
</div>