config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  resources :products, only: %i(index show)
  resources :categories, only: :show
  resources :carts, only: :index
  resources :orders, only: %i(index new create show)
  devise_for :users
  resource :user, only: :show
  namespace :admin do
    root "static_pages#home"

    resources :products
    resources :orders, only: %i(index show)
    resources :categories

    put "approve/:id", to: "orders#approve", as: :approve
    put "reject/:id", to: "orders#reject", as: :reject
  end

  get "add_cart/:product_id", to: "carts#add_cart", as: :add_cart
  get "remove_cart/:product_id", to: "carts#remove_cart", as: :remove_cart
  post "update_subtotal/", to: "carts#update_subtotal", as: :update_subtotal
  put "cancel/:id", to: "orders#cancel", as: :cancel
  get "filter/", to: "products#filter", as: :filter
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  authorize_resource class: false
  before_action :set_cart, :find_product, only: %i(add_cart remove_cart update_subtotal)
  before_action :load_products_in_cart, :load_quantity_in_cart, only: %i(index update_subtotal)

  def index; end

  def add_cart
    if session[:cart].key?(@product.id.to_s)
      session[:cart][@product.id.to_s] += Settings.quantity.one
    else
      session[:cart][@product.id.to_s] = Settings.quantity.one
    end

    respond_to do |format|
      format.html{render "static_pages/home"}
      format.json {}
      format.js
    end
  end

  def remove_cart
    session[:cart].delete(@product.id.to_s) if session[:cart].key? @product.id.to_s
    redirect_to carts_path
  end

  def update_subtotal
    session[:cart][params[:product_id].to_s] = params[:quantity].to_i
    @product.quantity_in_cart = params[:quantity].to_i

    respond_to do |format|
      format.html{render "carts/index"}
      format.json {}
      format.js
    end
  end

  private

  def find_product
    @product = Product.find_by id: params[:product_id]
    return if @product
    flash[:danger] = t "carts.couldnt_found"
    redirect_to root_path
  end
end

app/helpers/carts_helper.rb
# frozen_string_literal: true

module CartsHelper
  def set_cart
    @cart = session[:cart] ||= {}
  end

  def reset_cart
    session[:cart] = {}
  end

  def is_empty_cart?
    session[:cart].blank?
  end

  def sum_total_price
    @products_in_cart.collect{|product| product.quantity_in_cart * product.price}.sum
  end
end

app/views/carts/_cart_item.html.erb
<tr id="item_<%= product.id %>">
  <td data-th="Product" class="product">
    <div class="row">
      <div class="col-sm-2">
        <%= show_product_image product %>
      </div>
      <div class="col-sm-10">
        <h4><%= product.name %></h4>
      </div>
    </div>
  </td>
  <td data-th="Price" class="price"><%= number_to_currency product.price %></td>
  <td data-th="Quantity">
    <input type="number" class="form-control text-center quantity"
      min="<%= Settings.quantity.one %>" max="<%= product.quantity %>"
      value="<%= product.quantity_in_cart %>" data-product="<%= product.id %>">
  </td>
  <td data-th="Subtotal" class="subtotal">
    <%= number_to_currency product.price * product.quantity_in_cart %>
  </td>
  <td data-th="Delete" class="delete">
    <%= link_to content_tag(:i, "", class: "glyphicon glyphicon-trash").html_safe,
      remove_cart_path(product), class: "btn btn-danger btn-sm" %>
  </td>
</tr>

app/views/carts/add_cart.js.erb
$('.item_count').html('<%= session[:cart].size %>');
$('#cart_nav').attr('href', '<%= carts_path %>')

app/views/carts/index.html.erb
<table id="cart" class="table table-hover table-condensed">
  <thead>
    <tr>
      <th><%= t ".product" %></th>
      <th><%= t ".price" %></th>
      <th><%= t ".quantity" %></th>
      <th><%= t ".subtotal" %></th>
      <th><%= t ".delete" %></th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: "cart_item", collection: @products_in_cart, as: :product %>
  </tbody>
  <tfoot>
    <tr>
      <td>
        <%= link_to root_path, class: "btn btn-warning" do %>
          <i class="glyphicon glyphicon-arrow-left"></i>&nbsp;<%= t ".continue" %>
        <% end %>
      </td>
      <td colspan="2"></td>
      <td class="total_price">
        <div><%= t ".total" %></div>
        <div id="total"><%= number_to_currency sum_total_price %></div>
      </td>
      <td>
        <% unless is_empty_cart? %>
          <%= link_to new_order_path, class: "btn btn-success" do %>
            <%= t ".checkout" %>&nbsp;<i class="glyphicon glyphicon-arrow-right"></i>
          <% end %>
        <% end %>
      </td>
    </tr>
  </tfoot>
</table>
<%= javascript_include_tag "cart" %>

app/views/carts/update_subtotal.js.erb
$('#item_<%= @product.id %>>td.subtotal').html(
  '<%= number_to_currency (@product.price * @product.quantity_in_cart) %>');