config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  resources :products, only: %i(index show)
  resources :categories, only: :show
  resources :carts, only: :index
  resources :orders, only: %i(index new create show)
  devise_for :users
  resource :user, only: :show
  namespace :admin do
    root "static_pages#home"

    resources :products
    resources :orders, only: %i(index show)
    resources :categories

    put "approve/:id", to: "orders#approve", as: :approve
    put "reject/:id", to: "orders#reject", as: :reject
  end

  get "add_cart/:product_id", to: "carts#add_cart", as: :add_cart
  get "remove_cart/:product_id", to: "carts#remove_cart", as: :remove_cart
  post "update_subtotal/", to: "carts#update_subtotal", as: :update_subtotal
  put "cancel/:id", to: "orders#cancel", as: :cancel
  get "filter/", to: "products#filter", as: :filter
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  attr_accessor :quantity_in_cart

  belongs_to :category
  has_many :order_details, dependent: :destroy
  has_many :ratings, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :images, dependent: :destroy

  validates :name, presence: true, length: {maximum: Settings.name.length.maximum}
  validates :information, presence: true, length: {maximum: Settings.information.length.maximum}
  validates :price, :quantity, presence: true

  scope :by_active, ->{where active: true}
  scope :newest, ->{order created_at: :desc}
  scope :stocking, ->{where "quantity > ?", Settings.quantity.zero}
  scope :load_product_by_ids, ->(product_ids){where id: product_ids}
  scope :filter, ->(by_field, value_param) do
    case by_field
    when Settings.filter.alphabet
      order name: value_param
    when Settings.filter.price
      order price: value_param
    end
  end
end

app/controllers/admin/products_controller.rb
# frozen_string_literal: true

class Admin::ProductsController < AdminController
  load_and_authorize_resource
  before_action :load_products, only: :index
  before_action :load_product, except: %i(index new create)
  before_action :load_orders_in_processing, only: :destroy

  def index; end

  def show; end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new product_params
    if @product.save
      flash[:success] = t ".create_success"
      redirect_to admin_products_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @product.update product_params
      flash[:success] = t ".edit_success"
      redirect_to admin_products_path
    else
      render :edit
    end
  end

  def destroy
    ActiveRecord::Base.transaction do
      if @orders.present?
        @orders.find_each do |order|
          order.rejected!
          OrderMailer.reject_order(order).deliver_now
        end
      end
      @product.update! active: false
      flash[:success] = t ".delete_success"
      redirect_to admin_products_path
    end
  rescue StandardError
    flash[:danger] = t ".delete_failed"
    redirect_to admin_products_path
  end

  private

  def load_products
    @products = Product.stocking.by_active.newest.includes(:images)
                       .paginate page: params[:page], per_page: Settings.paginate.product.per_page
  end

  def load_product
    @product = Product.find_by id: params[:id]
    return if @product
    flash[:danger] = t ".couldnt_found"
    redirect_to root_path
  end

  def load_orders_in_processing
    @orders = Order.by_product_id(params[:id]).in_processing
  end

  def product_params
    params.require(:product).permit :category_id, :name, :information, :price, :quantity
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  load_and_authorize_resource
  before_action :load_products, only: %i(index filter)

  def index; end

  def show
    @product = Product.find_by id: params[:id]
    return if @product
    flash[:danger] = t "products.show.couldnt_found"
    redirect_to root_path
  end

  def filter
    @products = Product.by_active.stocking.includes(:images).filter(params[:filter], params[:order])
                       .paginate page: params[:page], per_page: Settings.paginate.product.per_page
    respond_to_format
  end

  private

  def load_products
    @q = Product.ransack params[:q]
    @products = @q.result.by_active.stocking.newest.includes(:images)
                  .paginate page: params[:page], per_page: Settings.paginate.product.per_page
  end

  def respond_to_format
    respond_to do |format|
      format.html{render "static_pages/home"}
      format.json {}
      format.js
    end
  end
end

app/views/admin/products/_form.html.erb
<%= form_for [:admin, @product] do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <%= f.label :category_id, t(".categories") %>
  <%= f.collection_select :category_id, @categories, :id, :name, {},
    class: "form-control" %>

  <%= f.label :name, t(".name") %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :information, t(".information") %>
  <%= f.text_area :information %>

  <%= f.label :price, t(".price") %>
  <%= f.text_field :price, class: "form-control" %>

  <%= f.label :quantity, t(".quantity") %>
  <%= f.text_field :quantity, class: "form-control" %>

  <%= f.submit t(".submit"), class: "btn btn-primary" %>
<% end %>

app/views/admin/products/_product.html.erb
<tr id="product_<%= product.id %>" class="text-center">
  <td><%= product.id %></td>
  <td><%= product.name %></td>
  <td><%= show_product_image product %></td>
  <td><%= number_to_currency product.price %></td>
  <td><%= product.quantity %></td>
  <td>
    <%= link_to edit_admin_product_path(product), class: "btn btn-info" do %>
      <i class="glyphicon glyphicon-edit"></i> <%= t ".edit" %>
    <% end %>
    <%= link_to admin_product_path(product), method: :delete,
      class: "btn btn-danger btn_delete_product" do %>
      <i class="glyphicon glyphicon-trash"></i> <%= t ".delete" %>
    <% end %>
  </td>
</tr>

app/views/admin/products/index.html.erb
<div class="row">
  <div class="col-md-12">
  <h1 class="text-center"><%= t ".products" %></h1>
  <div class="add-product">
    <%= link_to new_admin_product_path, class: "btn btn-success pull-right" do %>
      <i class="glyphicon glyphicon-plus"></i> <%= t ".create" %>
    <% end %>
  </div>
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th class="text-center"><%= t ".id" %></th>
        <th class="text-center"><%= t ".name" %></th>
        <th class="text-center"><%= t ".image" %></th>
        <th class="text-center"><%= t ".price" %></th>
        <th class="text-center"><%= t ".quantity" %></th>
        <th class="text-center"><%= t ".action" %></th>
      </tr>
    </thead>
    <tbody id="products">
      <%= render @products %>
    </tbody>
    <%= will_paginate %>
  </table>
</div>
</div>